tortuvshin/open-source-flutter-apps

README.md
- Added Sandwhich app to Intertainment (Entertainment?) section
- Added Sandwhich GIF
=> Update README to include Sandwhich

README.md
Changed the word `Intertainment` to `Entertainment`
=> Fixed typo in 'Intertainment'

README.md
There were few **_Grammar errors_** and **_few drawbacks_** which made it less efficient **_have been cleared_**
=> Please Update README.md File

README.md
Hello, in this PR I removed the Cingulo application from the list, since its repository is no longer available.
=> Removing nonexistent application

README.md
=> Add TV Randshow

README.md
DARK / LIGHT mode
Live News
Sort By catagory | country | NewsChannel
Find With Keyword
Using Rest API
=> Add NewsAPP

README.md
=> Add Enigma Signal Meter tool

README.md
Added Cab Sharing Portal App build by college students, for college students. 
Nicely maintained by coding club (DevClub) at IIT Delhi.
Great README for anyone to start contributing in open source projects.
Good for college students collaborating and engineering out the solutions. 
Link to the repo: https://github.com/devclub-iitd/ShareACab
Directory structure explained:
Relevant screenshots provided:
=> Added ShareACab in Travel section

README.md
This is one of my side projects which basically enables users to log their daily transactions and later this data can be used to get insights. It has all the major modules required for family finance management like accounts, categories, multi-currency support, etc. It is a multi-tenant app, and each tenant is considered as a family.
The project also includes a backend project built on .NET Core and SQL Server is used as the database.
=> Add piggyvault under finance

README.md
This is my project which enables the user to break his bank account into smaller branches and manage them efficiently by directly making transactions from a particular branch. The backend is made with Firebase.
=> Add bank_management under finance

README.md
Wallpaper App developed in Flutter using Pexels API
=> Add Wallbay under Personalization

README.md
A very nice project, by the way. Clean Architecture, uses BLoC.
=> Added Open Flutter E-Commerce App

README.md
Now, the ReceiptManager application is covered in this medium article released at "The Startup", Medium's largest active publication.
https://medium.com/swlh/fuzzy-receipt-parser-and-manager-cb614e4eaa6a
Even, the application is available in F-DROID.
https://apt.izzysoft.de/fdroid/index/apk/org.receipt_manager
The receipt parser app is a beautifully crafted application, to parse and manage receipts. It is written in dart and uses moor to store receipts permanently.
It is free and supports optical character recognition via tesseract. There are no paid features, nor advertisement.
All data is stored in the application and is not transferred to any server.
<p align="center">
</p>
=> Add the receipt manager application

README.md
👋 Could you add the flutter-finance app link to this repo?
`App:` https://github.com/shurygindv/currency-alarm
Happy holidays!
=> Added Currency Alarm app (finance)

README.md
Adding 3 new apps — Time Cop, a time tracker, and wger and Feeel, both fitness/workout apps
=> 7 new apps: Time Cop, wger, Feeel, and more

README.md
I added my app, Buwa (Black Unicorn Wallpapers) which you can find [here](https://github.com/iamtheblackunicorn/Buwa) in the `Personalization` section.
=> Added Black Unicorn Wallpapers

README.md
Hi, I added our app to the readme (Flutter WooCommerce App). You can find it in the **Shopping** section 🛍
=> Added Flutter WooCommerce App by WooSignal

README.md
Private, cross-platform package tracking app.
=> Add LibreTrack

README.md
=> updated readme description

README.md
[Space-Empires](https://www.github.com/satyamx64/space_empires) is a turn-based strategy game of 4X (abbreviation of Explore, Expand, Exploit, Exterminate) subgenre complemented with Decent UI and smooth animations. There are 8 Planets, and 4 Players ( 1 User + 3 Computer A.I). The objective is to win them all in under 365 turns. To do so, the player must manage their resources, make military, and win the war against other races. 
**Checklist**
=> Add Space Empires

README.md
=> Add One Second Diary

README.md
Simplifies comparing photos of tamper-evident seals and patterns using your eyes https://github.com/proninyaroslav/blink-comparison
**Checklist**
=> Add Blink Comparison app

README.md
Added - Doddle- (become an artist in a minute) in the Entertaiment Section
**Checklist**
=> Propose changes

README.md
I added my Stream Music Player in the Media Section.
**Checklist**
=> Stream Music Player

README.md
Added Tachidesk-Sorayomi in Entertainment section
A manga reader to read manga from a [Tachidesk-Server](https://github.com/Suwayomi/Tachidesk-Server) instance.
**Checklist**
=> Added Tachidesk-Sorayomi

README.md
I added my Movies App in the Media Section.
**Checklist**
=> Movies App

README.md
Added [MovieLab: Movies & TV Guide App](https://github.com/ErfanRht/MovieLab) in the Media Section.
**Checklist**
=> Add MovieLab

README.md
=> Added WorkoutTracker

README.md
=> Flutter Voting Dapp added

README.md
Add NetworkArch Flutter app to the tools category.
**Checklist**
=> Add NetworkArch

README.md
I have added an open source online game Arcade Plaza in the list. You can check it out from the bellow link https://github.com/aryamangodara/Arcade-Plaza 
**Checklist**
=> Added Arcade Plaza under games section

README.md
=> Added Aniflix project to the entertainment section

README.md
TubeCards is a flashcard platform that is seamlessly integrated with Youtube. It helps you learn from your favorite YouTubers by providing high-quality flashcards with just one click, bringing you science-based Spaced Repetition to retain knowledge.
**Checklist**
=> Add TubeCards

README.md
[Virlow Flutter Recorder](https://github.com/virlow-voice/virlow-flutter-recorder) - Voice recording and transcription plus it includes TL;DR, Short Hand Notes, and a rich text editor by [Virlow Voice](https://github.com/proninyaroslav](https://github.com/virlow-voice)
**Checklist**
=> Virlow Flutter Recorder adding new resource to README.md

README.md
=> RSA Encryption

README.md
First journal with Material 3 design! Spooky is a minimalist design application to write stories, journals, notes, diaries, todo, etc. We offer a variety of features that you can expect for your daily usage.
- Link to the repository: https://github.com/juniorise/spooky-mb
- Link to app atore: https://apps.apple.com/us/app/spooky/id1629372753?platform=iphone
- Link to play store: https://play.google.com/store/apps/details?id=com.juniorise.spooky
**Checklist**
=> Add Spooky Diary

README.md
Added [MMAS: Money Tracker](https://github.com/floranguyen0/mmas-money-tracker) in the Finance section.
**Checklist**
=> Add MMAS: Money Tracker

.idea/.gitignore, .idea/misc.xml, .idea/modules.xml, .idea/open-source-flutter-apps.iml, .idea/vcs.xml, README.md
**Checklist**
https://github.com/88srzh/comics_db
=> added my beatiful app

README.md
Added [NotePad](https://github.com/sarvesh4396/notepad) in productivity category
**Checklist**
=> add notepad

README.md
[Meditation App](https://github.com/Re4ch-Jay/Meditation_App) - An app that makes you calm, relief, relax, and focus 🧘 by [Phat Panhareach](https://github.com/Re4ch-Jay/).
**Checklist**
=> Meditation app

README.md
Budgeto is a personal finance management prototype app with categories such as needs, expenses, and savings and features like autopay, investments, and planning tools.
link to the repo - [https://github.com/tejasbadone/budgeto](https://github.com/tejasbadone/budgeto)
**Checklist**
=> add budgeto in finance

README.md
EasyWeather is a simple and user-friendly weather app that displays the current weather conditions of any place.
link to the repo - [https://github.com/tejasbadone/EasyWeather](https://github.com/tejasbadone/EasyWeather)
**Checklist**
=> Add EasyWeather in Tools

README.md
This powerful Android app allows you to easily convert plain text into highly secure ciphertext using popular ciphers such as Caesar, Affine, Playfair, and RSA. Safeguard your messages and ensure confidentiality with just a few taps.  
repo link -  https://github.com/musfique113/EncryptX
**Checklist**
=> added EncryptX app

README.md
BlackHole is a music player that can play songs from Youtube and Jiosaavan.
Link to the Repository: https://github.com/Sangwan5688/BlackHole
**Checklist**
=> Add BlackHole in Media

README.md
- Clarify what the app (now deployed 🎉 ) does 
- Update README.md for Open Food Facts
=> Update README.md for Open Food Facts

README.md
=> Added Openreads

README.md
Added Ejimo app: https://github.com/albemala/emoji-picker
**Checklist**
=> Added Ejimo app

README.md
Added Flutterzon App: [https://github.com/tejasbadone/flutterzon_bloc](https://github.com/tejasbadone/flutterzon_bloc)
**Checklist**
=> Added Flutterzon App in Shopping

README.md
=> get games flutter app added 

.idea/misc.xml, README.md
I just added a new project. This project simulates the operation of the Barrett 2090 and XV 3088 communication systems. It provides a user-friendly interface to experience the functionalities of these systems in a virtual environment. The simulation includes key features and controls to mimic real-world scenarios and interactions.
Project Screens:
=> feat: add flutter simulation new project

README.md
Add Flutter animations app
issue: #128
Sample flutter app to learn animations from basic to advanced
**Checklist**
- [🗸] I read [How to contribute](https://github.com/tortuvshin/open-source-flutter-apps/blob/master/CONTRIBUTING.md)
- [🗸] Added a link to the repo in the PR
=> feat: add Flutter Animations app

README.md
added Tasker: https://github.com/ErfanRht/Tasker
**Checklist**
=> added Tasker

README.md
Only Contacts is a simple Flutter app for managing contacts. It uses sqflite for local storage and ValueNotifier for state management, ensuring smooth performance and easy contact management.
**Checklist**
- [ ✔] I read [How to contribute](https://github.com/tortuvshin/open-source-flutter-apps/blob/master/CONTRIBUTING.md)
- [ ✔] Added a link to the repo in the PR
=> Add contact management app
